function BoutonHobbyOver(){
    d3.csv('villagers.csv',function(d){
        return {
        nom : d.Name,
        espece : d.Species,
        genre : d.Gender,
        personnalite : d.Personality,
        hobbie : d.Hobby,
        signe : d.Sign,
        style : d.Style1,
    }

    }).then(donnees =>{ 
        //variables nécessaires pour le Graphe
        const EspeceHobby = d3.group(donnees, d => d.signe, d => d.hobbie)
        const EspeceHobbyPerso = d3.group(donnees, d => d.signe, d=> d.hobbie, d=> d.personnalite)
        let Hobbies = EspeceHobbyPerso.get("Sagittarius")
        console.log(EspeceHobbyPerso)
        const Personnalite = [["Big Sister", "#94FFF6"],["Cranky", "#FBFF60" ],["Jock", "#FF40BB"],["Lazy", "#C840FF"],["Normal", "#4083FF"],["Peppy", "#40FF63"],["Smug", "#C92E2E"],["Snooty", "#FFC355"]]

        let GrapheX = milieuX +500
        let GrapheY = milieuY -300

        //fond blanc
        MonEspaceSVG.append("rect")
        .attr("id", "FondBlancHobby")
        .attr("x", GrapheX)
        .attr("y", GrapheY-50)
        .attr("width", 600)
        .attr("height", 650)
        .transition()
        .duration(1000) 
        .style('fill','white')
        .style('stroke','#4B4B6E')
        .style('stroke-width','3')
        .attr("rx", 8)
        .attr("ry", 8)
        .attr("opacity", 0.8)                

        // Les axes
        const xHobby = d3.scaleBand()
            .domain(["Education", "Fashion","Fitness",  "Music", "Nature", "Play"])
            .range([0, 500])
  
        let yHobby = d3.scaleLinear()
            .domain([0, 10])
            .range([650, 150]);        

        if (QuelMoisSommesNous == 1) {
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Sagittarius")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('x', milieuX+90 -HobbySignSignArrayOrdrePlus[0][1].length*5)
                .attr('y', milieuY+190 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteJaune")
                .attr('x', milieuX+90 + 70)
                .attr('y', milieuY+190 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            etoile_bleu.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('x', milieuX+60 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
                .attr('y', milieuY-190 -HobbySignSignArrayOrdrePlus[1][1].length*5) 
                
            let SpecieTexteBleu = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteBleu")
                .attr('x', milieuX+60 + 70)
                .attr('y', milieuY-190 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")
    
            etoile_rose.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
                .attr('x', milieuX-300 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
                .attr('y', milieuY-310 -HobbySignSignArrayOrdrePlus[2][1].length*5) 
                
            let SpecieTexteRose = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteRose")
                .attr('x', milieuX-300 + 70)
                .attr('y', milieuY-310 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")  

            etoile_vert.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
                .attr('x', milieuX-260 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
                .attr('y', milieuY+20 -HobbySignSignArrayOrdrePlus[3][1].length*5) 
                
            let SpecieTexteVert = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteVert")
                .attr('x', milieuX-260 + 70)
                .attr('y', milieuY+20 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")  

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Sagittarius")
        } else if(QuelMoisSommesNous == 2){
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Capricornus")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('x', milieuX -HobbySignSignArrayOrdrePlus[0][1].length*5)
                .attr('y', milieuY+190 -HobbySignSignArrayOrdrePlus[0][1].length*5)   
                
            let SpecieTexteJaune = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteJaune")
                .attr('x', milieuX + 70)
                .attr('y', milieuY+190 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            etoile_bleu.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('x', milieuX-130 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
                .attr('y', milieuY-190 -HobbySignSignArrayOrdrePlus[1][1].length*5) 
                
            let SpecieTexteBleu = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteBleu")
                .attr('x', milieuX-130 + 70)
                .attr('y', milieuY-190 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Capricornus")
        } else if(QuelMoisSommesNous == 3){ 
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Aquarius")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('x', milieuX+180 -HobbySignSignArrayOrdrePlus[0][1].length*5)
                .attr('y', milieuY+40 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteJaune")
                .attr('x', milieuX + 180 +70)
                .attr('y', milieuY+40 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            etoile_bleu.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('x', milieuX+150 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
                .attr('y', milieuY-150 -HobbySignSignArrayOrdrePlus[1][1].length*5) 
                
            let SpecieTexteBleu = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteBleu")
                .attr('x', milieuX+150+ 70)
                .attr('y', milieuY-150 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Aquarius")   
        } else if(QuelMoisSommesNous == 4){
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Pisces")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)
            
            etoile_jaune.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('x', milieuX+110-70 -HobbySignSignArrayOrdrePlus[0][1].length*5)
                .attr('y', milieuY+230 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteJaune")
                .attr('x', milieuX + 110 -70 +70)
                .attr('y', milieuY+230 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            etoile_bleu.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('x', milieuX+290-70 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
                .attr('y', milieuY-140 -HobbySignSignArrayOrdrePlus[1][1].length*5) 
                
            let SpecieTexteBleu = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteBleu")
                .attr('x', milieuX+290-70 + 70)
                .attr('y', milieuY-140 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")
    
            etoile_rose.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
                .attr('x', milieuX+30-70 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
                .attr('y', milieuY-180 -HobbySignSignArrayOrdrePlus[2][1].length*5) 
                
            let SpecieTexteRose = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteRose")
                .attr('x', milieuX+30-70 + 50)
                .attr('y', milieuY-180 + 50 -60 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")  

            etoile_vert.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
                .attr('x', milieuX-270-70 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
                .attr('y', milieuY-270 -HobbySignSignArrayOrdrePlus[3][1].length*5) 
                
            let SpecieTexteVert = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteVert")
                .attr('x', milieuX-270-70 + 50)
                .attr('y', milieuY-270 + 50 -50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Pisces")       
        } else if(QuelMoisSommesNous == 5){  
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Aries")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)
            
            etoile_jaune.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
                .attr('x', milieuX+130-150 -HobbySignSignArrayOrdrePlus[0][1].length*5)
                .attr('y', milieuY-220 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteJaune")
                .attr('x', milieuX+130-150 +70)
                .attr('y', milieuY-220 + 50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            etoile_bleu.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
                .attr('x', milieuX+150 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
                .attr('y', milieuY-250 -HobbySignSignArrayOrdrePlus[1][1].length*5) 
                
            let SpecieTexteBleu = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteBleu")
                .attr('x', milieuX+150 + 60)
                .attr('y', milieuY-250 -10 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")
    
            etoile_rose.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
                .attr('x', milieuX-450 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
                .attr('y', milieuY+2 -HobbySignSignArrayOrdrePlus[2][1].length*5) 
                
            let SpecieTexteRose = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteRose")
                .attr('x', milieuX-450 + 50)
                .attr('y', milieuY+2 + 50 -60 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5")  

            etoile_vert.transition()
                .duration(1000) 
                .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
                .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
                .attr('x', milieuX+375-150 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
                .attr('y', milieuY-190 -HobbySignSignArrayOrdrePlus[3][1].length*5) 
                
            let SpecieTexteVert = MonEspaceSVG.append('text')
                .attr('id', "SpecieTexteVert")
                .attr('x', milieuX+375-150 + 70)
                .attr('y', milieuY-190 +50 )    
                .attr('fill', "white")
                .attr('font-family', "AnimalCrossing")
                .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
                .attr('opacity', "0") 
                .transition() 
                .duration(1000)
                .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Aries")      
        } else if(QuelMoisSommesNous == 6){ 
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Taurus")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+65 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY+85 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+65 +60)
            .attr('y', milieuY+85 -10 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX-290 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY-300 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX-290 + 60)
            .attr('y', milieuY-300 -10 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-345 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-135 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-345 + 50)
            .attr('y', milieuY-135 + 50 -60 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")  

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Taurus")  
        } else if(QuelMoisSommesNous == 7){
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Gemini")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+120 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY+65 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+120 +60)
            .attr('y', milieuY+65 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX+100-HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY-340 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX+100+ 60)
            .attr('y', milieuY-340 -10 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-245 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-155 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-245 + 50)
            .attr('y', milieuY-155 + 50 -60 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")  

            etoile_vert.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('x', milieuX-230 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
            .attr('y', milieuY+100 -HobbySignSignArrayOrdrePlus[3][1].length*5) 

            let SpecieTexteVert = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteVert")
            .attr('x', milieuX-230 + 70)
            .attr('y', milieuY+100 +50 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Gemini")   
        } else if(QuelMoisSommesNous == 8){ 
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Cancer")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+145 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY+65 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+145 +60)
            .attr('y', milieuY+65 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX-60-HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY-380 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX-60+ 60)
            .attr('y', milieuY-380 -10 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-45 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-135 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-45 + 50)
            .attr('y', milieuY-135 + 50 -60 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")  

            etoile_vert.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('x', milieuX-190 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
            .attr('y', milieuY+210 -HobbySignSignArrayOrdrePlus[3][1].length*5) 

            let SpecieTexteVert = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteVert")
            .attr('x', milieuX-190 + 70)
            .attr('y', milieuY+210 +50 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Cancer")  
        } else if(QuelMoisSommesNous == 9){ 
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Leo")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+228 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY+259 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+228 +60)
            .attr('y', milieuY+259 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX-295-HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY-345 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX-295+ 60)
            .attr('y', milieuY-345 -10 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-140 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-145 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-140 + 55)
            .attr('y', milieuY-145 + 50 -55 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")  

            etoile_vert.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('x', milieuX-315 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
            .attr('y', milieuY -HobbySignSignArrayOrdrePlus[3][1].length*5) 

            let SpecieTexteVert = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteVert")
            .attr('x', milieuX-315 + 55)
            .attr('y', milieuY -5 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            // Diagrammes en babres
            yHobby
            .domain([0, 11])
            .range([650, 100]);      
            Hobbies = EspeceHobbyPerso.get("Leo")             
        } else if(QuelMoisSommesNous == 10){
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Virgo")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+42 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY+20 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+42 +60)
            .attr('y', milieuY+20 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX+115-HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY-270 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX+115+ 55)
            .attr('y', milieuY-270 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-177 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-175 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-177 + 55)
            .attr('y', milieuY-175 + 50 -60 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")  

            etoile_vert.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('x', milieuX+70 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
            .attr('y', milieuY+358 -HobbySignSignArrayOrdrePlus[3][1].length*5) 

            let SpecieTexteVert = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteVert")
            .attr('x', milieuX+70 + 50)
            .attr('y', milieuY+358 -5 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Virgo")              
        } else if(QuelMoisSommesNous == 11){ 
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Libra")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+32 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY-85 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+32 +60)
            .attr('y', milieuY-85 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX+166-HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY+40 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX+166+ 55)
            .attr('y', milieuY+40 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-152 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-225 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-152 + 55)
            .attr('y', milieuY-225 + 50 -60 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")  

            etoile_vert.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[3][1].length*10)
            .attr('x', milieuX-117 -HobbySignSignArrayOrdrePlus[3][1].length*5 )
            .attr('y', milieuY+148 -HobbySignSignArrayOrdrePlus[3][1].length*5) 

            let SpecieTexteVert = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteVert")
            .attr('x', milieuX-117 + 50)
            .attr('y', milieuY+148 -5 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[3][1].length + " " + HobbySignSignArrayOrdrePlus[3][0] )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Libra")   
        } else if(QuelMoisSommesNous == 12){
            //déplacement des étoiles 
            const HobbySignSign = EspeceHobby.get("Scorpio")
            let HobbySignSignArray = Array.from(HobbySignSign)
            let HobbySignSignArrayOrdreMoins = d3.sort(HobbySignSignArray, (d) => d[1].length)
            HobbySignSignArrayOrdrePlus=  d3.reverse(HobbySignSignArrayOrdreMoins)

            etoile_jaune.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[0][1].length*10)
            .attr('x', milieuX+32 -200 -HobbySignSignArrayOrdrePlus[0][1].length*5)
            .attr('y', milieuY-105 -HobbySignSignArrayOrdrePlus[0][1].length*5)   

            let SpecieTexteJaune = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteJaune")
            .attr('x', milieuX+32 -200 +60)
            .attr('y', milieuY-105 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[0][1].length + " " + HobbySignSignArrayOrdrePlus[0][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            etoile_bleu.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[1][1].length*10)
            .attr('x', milieuX+106 -200 -HobbySignSignArrayOrdrePlus[1][1].length*5 )
            .attr('y', milieuY+60 -HobbySignSignArrayOrdrePlus[1][1].length*5) 

            let SpecieTexteBleu = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteBleu")
            .attr('x', milieuX+106 -200 + 55)
            .attr('y', milieuY+60 -15 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[1][1].length + " " + HobbySignSignArrayOrdrePlus[1][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5")

            etoile_rose.transition()
            .duration(1000) 
            .attr('height', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('width', 50 + HobbySignSignArrayOrdrePlus[2][1].length*10)
            .attr('x', milieuX-152 -200 -HobbySignSignArrayOrdrePlus[2][1].length*5 )
            .attr('y', milieuY-245 -HobbySignSignArrayOrdrePlus[2][1].length*5) 

            let SpecieTexteRose = MonEspaceSVG.append('text')
            .attr('id', "SpecieTexteRose")
            .attr('x', milieuX-152 -200 )
            .attr('y', milieuY-245 + 50 -85 )    
            .attr('fill', "white")
            .attr('font-family', "AnimalCrossing")
            .text(HobbySignSignArrayOrdrePlus[2][1].length + " " + HobbySignSignArrayOrdrePlus[2][0]  )
            .attr('opacity', "0") 
            .transition() 
            .duration(1000)
            .attr('opacity', "0.5") 

            // Diagrammes en babres
            Hobbies = EspeceHobbyPerso.get("Scorpio")
        } 
        // Diagramme en barre selon :  SIGNE - HOBBY - PERSONNALITE
                // variables nécessaires pour le diagramme en barre 
                let HobbiesArray = Array.from(Hobbies)
                HobbiesArray.sort(d3.ascending) 
                console.log(Hobbies) 
                    
                MonEspaceSVG.append("g") 
                    .attr("id", "AxeXHobby")
                    .attr("transform", `translate(${GrapheX+50},${GrapheY+550})`)
                    .call(d3.axisBottom(xHobby))
                    .attr('font-family', "AnimalCrossing")
                    .attr("opacity", 0) 
                    .transition()
                    .duration(1000) 
                    .attr("opacity",1)       

                MonEspaceSVG.append("g") 
                    .attr("id", "AxeYHobby")
                    .attr("transform", `translate(${GrapheX+50},${GrapheY-100})`)
                    .call(d3.axisLeft(yHobby))
                    .attr('font-family', "AnimalCrossing") 
                    .attr("opacity", 0) 
                    .transition()
                    .duration(1000) 
                    .attr("opacity",1)

                //barre
                let HobbyHauteur =0
                for (let i = 0; i < 6; i++) {
                    let HobbyHauteur =0
                    let HobbyArrayArray = Array.from(HobbiesArray[i][1])
                    for (let a = 0; a < HobbyArrayArray.length; a++) {
                        MonEspaceSVG.append("rect")
                            .attr("id", "rectHobby" + i  + a)
                            .attr("x", GrapheX+70 + i*50 + 32*i)
                            .attr("y", GrapheY  - HobbyArrayArray[a][1].length*50 - HobbyHauteur*50 +550)
                            .attr("width", 50)
                            .attr("height", HobbyArrayArray[a][1].length*50)
                            .transition()
                                .duration(1000) 
                                .attr("opacity", 0.8)
                    HobbyHauteur += HobbyArrayArray[a][1].length
                        //couleur
                        for (let c = 0; c < Personnalite.length; c++) {
                            if (HobbyArrayArray[a][0] == Personnalite[c][0]) {
                            let rectangle = document.getElementById(`rectHobby${i}${a}`) 
                            rectangle.style = `fill : ${Personnalite[c][1]}`;      
                            }
                        }
                    }
                }
                //label 
                for (let a = 0; a < 4; a++) {
                    MonEspaceSVG.append("rect")
                    .attr("id", "rectHobbylabel" + a)
                    .attr("x", GrapheX+130 + a*100)
                    .attr("y", GrapheY -30)
                    .attr("width", 20)
                    .attr("height", 20)
                    .transition()
                        .duration(1000) 
                        .attr("opacity", 0.8) 
                
                    MonEspaceSVG.append("text")
                    .attr("id", "lab1" + a)
                    .attr("x", GrapheX+130 + a*100 +30)
                    .attr("y", GrapheY-15)
                    .attr("opacity", 0) 
                    .text(Personnalite[a][0])
                    .style("font-size", "15px")  
                    .attr('font-family', "AnimalCrossing")    
                    .style("fill", "black")
                    .transition()
                    .duration(1000)
                    .attr("opacity", 1)
                        
                let rectangle = document.getElementById(`rectHobbylabel${a}`) 
                rectangle.style = `fill : ${Personnalite[a][1]}`;  
                }   
                
                for (let a = 4; a < 8; a++) {
                    MonEspaceSVG.append("rect")
                    .attr("id", "rectHobbylabel" + a)
                    .attr("x", GrapheX+130 + a*100 -400)
                    .attr("y", GrapheY)
                    .attr("width", 20)
                    .attr("height", 20)
                    .transition()
                        .duration(1000) 
                        .attr("opacity", 0.8) 
                
                    MonEspaceSVG.append("text")
                    .attr("id", "lab1" + a)
                    .attr("x", GrapheX+130 + a*100 +30 -400)
                    .attr("y", GrapheY+15)
                    .attr("opacity", 0) 
                    .text(Personnalite[a][0])
                    .style("font-size", "15px")  
                    .attr('font-family', "AnimalCrossing")    
                    .style("fill", "black")
                    .transition()
                        .duration(1000)
                        .attr("opacity", 1)
                             
                let rectangle = document.getElementById(`rectHobbylabel${a}`) 
                rectangle.style = `fill : ${Personnalite[a][1]}`;  
                }   
    })

}