// A SUPPRIMER QUAND LE CODE SERA FINI


//déplacer les grandes étoiles
etoile_jaune.transition()
.duration(1000) 
.attr('x', milieuX+90)
.attr('y', milieuY+190) 

etoile_rose.transition()
.duration(1000) 
.attr('x', milieuX-300)
.attr('y', milieuY-310) 

etoile_vert.transition()
.duration(1000) 
.attr('x', milieuX-260)
.attr('y', milieuY+20) 

etoile_bleu.transition()
.duration(1000) 
.attr('x', milieuX+60)
.attr('y', milieuY-190)  

//les traits
trait1
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition()
.attr('x1', milieuX +90)
.attr('y1', milieuY -145)
.attr('x2', milieuX + 140)
.attr('y2', milieuY +30)
.attr('stroke-opacity', .1)
.transition()
.duration(1000)
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait2
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition()
.attr('x1', milieuX +110)
.attr('y1', milieuY +210)
.attr('x2', milieuX + 140)
.attr('y2', milieuY +30)
.attr('stroke-opacity', .1)
.transition()
.duration(1000) 
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait3
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX +90)
.attr('y1', milieuY -145)
.attr('x2', milieuX+210)
.attr('y2', milieuY-320)
.attr('stroke-opacity', .1)
.transition()
.duration(1000) 
.attr('stroke-opacity', .5)
.attr("stroke", "white")


trait4
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX +280)
.attr('y1', milieuY +60)
.attr('x2', milieuX + 140)
.attr('y2', milieuY +30)
.attr('stroke-opacity', .1)
.transition()
.duration(1000) 
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait5
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX +70)
.attr('y1', milieuY -155)
.attr('x2', milieuX -80)
.attr('y2', milieuY -85)
.attr('stroke-opacity', .1)
.transition()
.duration(1000) 
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait6
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX-170)
.attr('y1', milieuY-110)
.attr('x2', milieuX -80)
.attr('y2', milieuY +-85)
.attr('stroke-opacity', .1)
.transition()
.duration(1000) 
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait7
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX-170)
.attr('y1', milieuY-110)
.attr('x2', milieuX -280)
.attr('y2', milieuY -40)
.attr('stroke-opacity', .1)
.transition()
.duration(1000) 
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait8
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX-240)
.attr('y1', milieuY+40)
.attr('x2', milieuX -280)
.attr('y2', milieuY -40)
.attr('stroke-opacity', .1)
.transition()
.duration(1000)
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait9
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX-170)
.attr('y1', milieuY-110)
.attr('x2', milieuX -280)
.attr('y2', milieuY -290)
.attr('stroke-opacity', .1)
.transition()
.duration(1000)
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait10
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX-210)
.attr('y1', milieuY-320)
.attr('x2', milieuX -280)
.attr('y2', milieuY -290)
.attr('stroke-opacity', .1)
.transition()
.duration(1000)
.attr('stroke-opacity', .5)
.attr("stroke", "white")  

trait11
.transition()
.duration(500) 
.attr("stroke", "#0f0f3d")
.transition() 
.attr('x1', milieuX+100)
.attr('y1', milieuY+210)
.attr('x2', milieuX +160)
.attr('y2', milieuY +320)
.attr('stroke-opacity', .1)
.transition()
.duration(1000)
.attr('stroke-opacity', .5)
.attr("stroke", "white") 

// les étoiles
étoile1.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX - 280)
.attr('cy',milieuY-40)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile2.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX - 170)
.attr('cy',milieuY- 110)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile3.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX - 80)
.attr('cy',milieuY-85)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile4.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX - 210)
.attr('cy',milieuY- 320)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile5.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX+210)
.attr('cy',milieuY-320)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile6.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX + 140)
.attr('cy',milieuY +30)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile7.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX+280)
.attr('cy',milieuY+60)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  

étoile8.transition()
.duration(500) 
.attr("fill", "#0f0f3d")
.transition() 
.attr('cx',milieuX+160 )
.attr('cy',milieuY+320)
.attr('r', 5)
.transition()
.duration(1000)
.attr("fill", "white")  